import { Platform } from 'react-native';

export default [
  {
    key: '0',
    name: 'waves',
    type: 'material-community',
    label: 'Lake View',
    onPress: () => {},
  },
  {
    key: '1',
    name: 'weather-sunny',
    type: 'material-community',
    label: 'Outdoor',
    onPress: () => {},
  },
  {
    key: '2',
    name: 'city',
    type: 'material-community',
    label: 'Downtown',
    onPress: () => {},
  },
  {
    key: '3',
    name: 'hamburger',
    type: 'material-community',
    label: 'American',
    onPress: () => {},
  },
  {
    key: '4',
    name: Platform.OS === 'ios' ? 'ios-pizza' : 'md-pizza',
    type: 'ionicon',
    label: 'Pizza',
    onPress: () => {},
  },
  {
    key: '5',
    name: 'silverware-variant',
    type: 'material-community',
    label: 'Italian',
    onPress: () => {},
  },
  {
    key: '6',
    name: 'knife',
    type: 'material-community',
    label: 'Steak',
    onPress: () => {},
  },
  {
    key: '7',
    name: Platform.OS === 'ios' ? 'ios-egg' : 'md-egg',
    type: 'ionicon',
    label: 'Breakfast',
    onPress: () => {},
  },
  {
    key: '8',
    name: 'taco',
    type: 'material-community',
    label: 'Mexican',
    onPress: () => {},
  },
  {
    key: '9',
    name: 'glass-mug',
    type: 'material-community',
    label: 'Bar',
    onPress: () => {},
  },
  {
    key: '10',
    name: 'bowl',
    type: 'material-community',
    label: 'Seafood',
    onPress: () => {},
  },
  {
    key: '11',
    name: 'rice',
    type: 'material-community',
    label: 'Sushi',
    onPress: () => {},
  },
  {
    key: '12',
    name: Platform.OS === 'ios' ? 'ios-ice-cream' : 'md-ice-cream',
    type: 'ionicon',
    label: 'Desserts',
    onPress: () => {},
  },
  {
    key: '13',
    name: 'cupcake',
    type: 'material-community',
    label: 'Bakery',
    onPress: () => {},
  },
  {
    key: '14',
    name: 'owl',
    type: 'material-community',
    label: 'Late Night',
    onPress: () => {},
  },
  {
    key: '15',
    name: 'food',
    type: 'material-community',
    label: 'Sandwich',
    onPress: () => {},
  },
  {
    key: '16',
    name: 'hops',
    type: 'material-community',
    label: 'Brewery',
    onPress: () => {},
  },
  {
    key: '17',
    name: 'dog-side',
    type: 'material-community',
    label: 'Dog Friendly',
    onPress: () => {},
  },
  {
    key: '18',
    name: 'truck-fast',
    type: 'material-community',
    label: 'Delivery',
    onPress: () => {},
  },
];
