import { Platform } from 'react-native';

import { EATERY } from '../../categories';

import {
  LAKE_VIEW,
  OUTDOOR,
  BREAKFAST,
  BAKERY,
  AMERICAN,
  PIZZA,
  MEXICAN,
  SANDWHICH,
  BREWERY,
  DOWNTOWN,
  BAR,
  STEAK,
  ITALIAN,
  SEAFOOD,
  SUSHI,
  COFFEE,
  DESSERT,
  DELIVERY,
  DOG_FRIENDLY,
  LATE_NIGHT,
} from '../../types/group_types';

const category = EATERY;

// const color = '#e17055';
const color = 'rgba(214, 48, 49, 0.75)';

export default [
  {
    key: LAKE_VIEW,
    name: 'waves',
    type: 'material-community',
    label: 'Lake View',
    category,
    color,
  },
  {
    key: OUTDOOR,
    name: 'weather-sunny',
    type: 'material-community',
    label: 'Outdoor',
    category,
    color,
  },
  {
    key: DOWNTOWN,
    name: 'city',
    type: 'material-community',
    label: 'Downtown',
    category,
    color,
  },
  {
    key: AMERICAN,
    name: 'hamburger',
    type: 'material-community',
    label: 'American',
    category,
    color,
  },
  {
    key: PIZZA,
    name: Platform.OS === 'ios' ? 'ios-pizza' : 'md-pizza',
    type: 'ionicon',
    label: 'Pizza',
    category,
    color,
  },
  {
    key: ITALIAN,
    name: 'silverware-variant',
    type: 'material-community',
    label: 'Italian',
    category,
    color,
  },
  {
    key: STEAK,
    name: 'knife',
    type: 'material-community',
    label: 'Steak',
    category,
    color,
  },
  {
    key: BREAKFAST,
    name: Platform.OS === 'ios' ? 'ios-egg' : 'md-egg',
    type: 'ionicon',
    label: 'Breakfast',
    category,
    color,
  },
  {
    key: MEXICAN,
    name: 'taco',
    type: 'material-community',
    label: 'Mexican',
    category,
    color,
  },
  {
    key: BAR,
    name: 'glass-mug',
    type: 'material-community',
    label: 'Bar',
    category,
    color,
  },
  {
    key: COFFEE,
    name: 'coffee',
    type: 'material-community',
    label: 'Coffee',
    category,
    color,
  },
  {
    key: SEAFOOD,
    name: 'bowl',
    type: 'material-community',
    label: 'Seafood',
    category,
    color,
  },
  {
    key: SUSHI,
    name: 'rice',
    type: 'material-community',
    label: 'Sushi',
    category,
    color,
  },
  {
    key: DESSERT,
    name: Platform.OS === 'ios' ? 'ios-ice-cream' : 'md-ice-cream',
    type: 'ionicon',
    label: 'Desserts',
    category,
    color,
  },
  {
    key: BAKERY,
    name: 'cupcake',
    type: 'material-community',
    label: 'Bakery',
    category,
    color,
  },
  {
    key: LATE_NIGHT,
    name: 'owl',
    type: 'material-community',
    label: 'Late Night',
    category,
    color,
  },
  {
    key: SANDWHICH,
    name: 'food',
    type: 'material-community',
    label: 'Sandwich',
    category,
    color,
  },
  {
    key: BREWERY,
    name: 'hops',
    type: 'material-community',
    label: 'Brewery',
    category,
    color,
  },
  {
    key: DOG_FRIENDLY,
    name: 'dog-side',
    type: 'material-community',
    label: 'Dog Friendly',
    category,
    color,
  },
  {
    key: DELIVERY,
    name: 'truck-fast',
    type: 'material-community',
    label: 'Delivery',
    category,
    color,
  },
];
