import { Platform } from 'react-native';
import { WebBrowser } from 'expo';

import {
  SPORT, ENTERTAINMENT, NATURE, EATERY,
} from '../../categories';

import {
  BIKE,
  HIKING,
  PARKS,
  BEACHES,
  BREWERY,
  DOWNTOWN,
  WINERY,
  THEATER,
  DOG_FRIENDLY,
  NIGHT_LIFE,
  ART,
  GYM,
  GOLF,
  SKIING,
  MARINA,
  LAKES,
} from '../../types/group_types';

// const color = '#0984e3';
const color = 'rgba(9, 132, 227, 0.75)';

export default [
  {
    key: BIKE,
    name: 'bike',
    type: 'material-community',
    label: 'Bike Trails',
    category: SPORT,
    onPress: () => WebBrowser.openBrowserAsync('https://traversetrails.org/'),
    color,
  },
  {
    key: HIKING,
    name: 'terrain',
    type: 'material-community',
    label: 'Hiking',
    category: SPORT,
    onPress: () => WebBrowser.openBrowserAsync('https://www.traversecity.com/outdoors/hiking/'),
    color,
  },
  {
    key: BEACHES,
    name: 'beach',
    type: 'material-community',
    label: 'Beaches',
    category: NATURE,
    color,
  },
  {
    key: LAKES,
    name: 'waves',
    type: 'material-community',
    label: 'Lakes',
    category: NATURE,
    onPress: () => WebBrowser.openBrowserAsync(
      'https://mynorth.com/2017/08/10-best-northern-michigan-inland-lakes/',
    ),
    color,
  },
  {
    key: MARINA,
    name: Platform.OS === 'ios' ? 'ios-boat' : 'md-boat',
    type: 'ionicon',
    label: 'Marinas',
    category: NATURE,
    color,
  },
  {
    key: SKIING,
    name: 'snowflake',
    type: 'material-community',
    label: 'Skiing',
    category: SPORT,
    color,
  },
  {
    key: BREWERY,
    name: Platform.OS === 'ios' ? 'ios-beer' : 'md-beer',
    type: 'ionicon',
    label: 'Breweries',
    category: EATERY,
    color,
  },
  {
    key: WINERY,
    name: Platform.OS === 'ios' ? 'ios-wine' : 'md-wine',
    type: 'ionicon',
    label: 'Wineries',
    category: EATERY,
    color,
  },
  {
    key: THEATER,
    name: 'ticket',
    type: 'material-community',
    label: 'Theater',
    category: ENTERTAINMENT,
    color,
  },
  {
    key: PARKS,
    name: 'flower',
    type: 'material-community',
    label: 'Parks',
    category: NATURE,
    color,
  },
  {
    key: NIGHT_LIFE,
    name: 'glass-cocktail',
    type: 'material-community',
    label: 'Nightlife',
    category: EATERY,
    color,
  },
  {
    key: ART,
    name: Platform.OS === 'ios' ? 'ios-brush' : 'md-brush',
    type: 'ionicon',
    label: 'Art',
    category: ENTERTAINMENT,
    color,
  },
  {
    key: GOLF,
    name: 'golf',
    type: 'material-community',
    label: 'Golf',
    category: SPORT,
    color,
  },
  {
    key: GYM,
    name: Platform.OS === 'ios' ? 'ios-fitness' : 'md-fitness',
    type: 'ionicon',
    label: 'Gyms',
    category: SPORT,
    color,
  },
  {
    key: DOG_FRIENDLY,
    name: Platform.OS === 'ios' ? 'ios-paw' : 'md-paw',
    type: 'ionicon',
    label: 'Dog Friendly',
    category: EATERY,
    color,
  },
  {
    key: DOWNTOWN,
    name: 'city',
    type: 'material-community',
    label: 'Downtown',
    category: ENTERTAINMENT,
    color,
  },
];
