import { Platform } from 'react-native';

export default [
  {
    key: '0',
    name: 'bike',
    type: 'material-community',
    label: 'Bike Trails',
    onPress: () => {},
  },
  {
    key: '1',
    name: 'terrain',
    type: 'material-community',
    label: 'Hiking',
    onPress: () => {},
  },
  {
    key: '2',
    name: 'beach',
    type: 'material-community',
    label: 'Beaches',
    onPress: () => {},
  },
  {
    key: '3',
    name: 'waves',
    type: 'material-community',
    label: 'Lakes',
    onPress: () => {},
  },
  {
    key: '4',
    name: 'snowflake',
    type: 'material-community',
    label: 'Skiing',
    onPress: () => {},
  },
  {
    key: '5',
    name: Platform.OS === 'ios' ? 'ios-beer' : 'md-beer',
    type: 'ionicon',
    label: 'Breweries',
    onPress: () => {},
  },
  {
    key: '6',
    name: Platform.OS === 'ios' ? 'ios-wine' : 'md-wine',
    type: 'ionicon',
    label: 'Wineries',
    onPress: () => {},
  },
  {
    key: '7',
    name: 'ticket',
    type: 'material-community',
    label: 'Theater',
    onPress: () => {},
  },
  {
    key: '8',
    name: 'flower',
    type: 'material-community',
    label: 'Parks',
    onPress: () => {},
  },
  {
    key: '9',
    name: 'glass-cocktail',
    type: 'material-community',
    label: 'Nightlife',
    onPress: () => {},
  },
  {
    key: '10',
    name: Platform.OS === 'ios' ? 'ios-brush' : 'md-brush',
    type: 'ionicon',
    label: 'Art',
    onPress: () => {},
  },
  {
    key: '11',
    name: 'golf',
    type: 'material-community',
    label: 'Golf',
    onPress: () => {},
  },
  {
    key: '12',
    name: 'dumbbell',
    type: 'material-community',
    label: 'Gyms',
    onPress: () => {},
  },
  {
    key: '13',
    name: Platform.OS === 'ios' ? 'ios-paw' : 'md-paw',
    type: 'ionicon',
    label: 'Dog Friendly',
    onPress: () => {},
  },
];
