import { Platform } from 'react-native';
import { WebBrowser } from 'expo';

import {
  TRANSPORTATION, SPORT, ENTERTAINMENT, NATURE, EATERY, LANDMARK,
} from '../../categories';

import {
  COFFEE,
  FARMS,
  BEACHES,
  SHOPPING,
  PARKING,
  DIRECTIONS,
  BUS,
  SKIING,
  GOLF,
  COMMONS,
  TOURS,
  CAR_TRIPS,
  TAXI,
  LIGHTHOUSES,
} from '../../types/group_types';

// const color = '#fdcb6e';
const color = 'rgba(253, 203, 110, 0.75)';

export default [
  {
    key: 'EVENTS',
    name: Platform.OS === 'ios' ? 'ios-calendar' : 'md-calendar',
    type: 'ionicon',
    label: 'Events',
    onPress: () => WebBrowser.openBrowserAsync('https://www.traversecity.com/events/'),
    color,
  },
  {
    key: PARKING,
    name: 'parking',
    type: 'material-community',
    label: 'Parking',
    onPress: () => WebBrowser.openBrowserAsync('https://www.downtowntc.com/maps-parking/parking-map'),
    color,
  },
  {
    key: DIRECTIONS,
    name: 'routes',
    type: 'material-community',
    label: 'Directions',
    onPress: () => WebBrowser.openBrowserAsync(
      'https://www.traversecity.com/plan/about-traverse-city/driving-distances/',
    ),
    color,
  },
  {
    key: 'WEATHER',
    name: Platform.OS === 'ios' ? 'ios-sunny' : 'md-sunny',
    type: 'ionicon',
    label: 'Weather',
    color,
  },
  {
    key: BUS,
    name: Platform.OS === 'ios' ? 'ios-bus' : 'md-bus',
    type: 'ionicon',
    label: 'Bus',
    // category: TRANSPORTATION,
    onPress: () => WebBrowser.openBrowserAsync('http://www.bata.net/'),
    color,
  },
  {
    key: 'LAKE_INFO',
    name: 'waves',
    type: 'material-community',
    label: 'Lake Info',
    onPress: () => WebBrowser.openBrowserAsync('https://www.ndbc.noaa.gov/station_page.php?station=gtrm4'),
    color,
  },
  {
    key: COFFEE,
    name: 'coffee',
    type: 'material-community',
    label: 'Coffee',
    category: EATERY,
    color,
  },
  {
    key: SKIING,
    name: Platform.OS === 'ios' ? 'ios-snow' : 'md-snow',
    type: 'ionicon',
    label: 'Skiing',
    category: SPORT,
    color,
  },
  {
    key: GOLF,
    name: 'golf',
    type: 'material-community',
    label: 'Golf',
    category: SPORT,
    color,
  },
  {
    key: COMMONS,
    name: 'city-variant',
    type: 'material-community',
    label: 'Commons',
    category: LANDMARK,
    color,
    onPress: () => WebBrowser.openBrowserAsync('https://www.thevillagetc.com/'),
  },
  {
    key: BEACHES,
    name: 'beach',
    type: 'material-community',
    label: 'Beaches',
    category: NATURE,
    color,
  },
  {
    key: TOURS,
    name: 'van-passenger',
    type: 'material-community',
    label: 'Tours',
    category: TRANSPORTATION,
    color,
    onPress: () => WebBrowser.openBrowserAsync('https://wineandbeertours.com/'),
  },
  {
    key: SHOPPING,
    name: Platform.OS === 'ios' ? 'shopping' : 'shopping',
    type: 'material-community',
    label: 'Shopping',
    category: ENTERTAINMENT,
    color,
  },
  {
    key: CAR_TRIPS,
    name: 'road-variant',
    type: 'material-community',
    label: 'Car Trips',
    // category: TRANSPORTATION,
    onPress: () => WebBrowser.openBrowserAsync(
      'https://cdn.shopify.com/s/files/1/1230/6922/files/30_Roadtrip_M-22.pdf?13376906829999686641',
    ),
    color,
  },
  {
    key: TAXI,
    name: 'taxi',
    type: 'material-community',
    label: 'Taxi',
    category: TRANSPORTATION,
    color,
  },
  {
    key: FARMS,
    name: 'tractor',
    type: 'material-community',
    label: 'Farms',
    category: NATURE,
    color,
  },
  {
    key: LIGHTHOUSES,
    name: 'lighthouse',
    type: 'material-community',
    label: 'Lighthouses',
    category: LANDMARK,
    color,
  },
  {
    key: 'ABOUT',
    name:
      Platform.OS === 'ios' ? 'ios-information-circle-outline' : 'md-information-circle-outline',
    type: 'ionicon',
    label: 'About',
    color,
  },
];
