import { Platform } from 'react-native';

export default [
  {
    key: 'LAKE_VIEW',
    name: 'waves',
    type: 'material-community',
    label: 'Lake View',
    onPress: () => {},
  },
  {
    key: 'OUTDOOR',
    name: 'weather-sunny',
    type: 'material-community',
    label: 'Outdoor',
    onPress: () => {},
  },
  {
    key: 'DOWNTOWN',
    name: 'city',
    type: 'material-community',
    label: 'Downtown',
    onPress: () => {},
  },
  {
    key: 'AMERICAN',
    name: 'hamburger',
    type: 'material-community',
    label: 'American',
    onPress: () => {},
  },
  {
    key: 'PIZZA',
    name: Platform.OS === 'ios' ? 'ios-pizza' : 'md-pizza',
    type: 'ionicon',
    label: 'Pizza',
    onPress: () => {},
  },
  {
    key: 'ITALIAN',
    name: 'silverware-variant',
    type: 'material-community',
    label: 'Italian',
    onPress: () => {},
  },
  {
    key: 'STEAK',
    name: 'knife',
    type: 'material-community',
    label: 'Steak',
    onPress: () => {},
  },
  {
    key: 'BREAKFAST',
    name: Platform.OS === 'ios' ? 'ios-egg' : 'md-egg',
    type: 'ionicon',
    label: 'Breakfast',
    onPress: () => {},
  },
  {
    key: 'MEXICAN',
    name: 'taco',
    type: 'material-community',
    label: 'Mexican',
    onPress: () => {},
  },
  {
    key: 'BAR',
    name: 'glass-mug',
    type: 'material-community',
    label: 'Bar',
    onPress: () => {},
  },
  {
    key: 'SEAFOOD',
    name: 'bowl',
    type: 'material-community',
    label: 'Seafood',
    onPress: () => {},
  },
  {
    key: 'SUSHI',
    name: 'rice',
    type: 'material-community',
    label: 'Sushi',
    onPress: () => {},
  },
  {
    key: 'DESSERT',
    name: Platform.OS === 'ios' ? 'ios-ice-cream' : 'md-ice-cream',
    type: 'ionicon',
    label: 'Desserts',
    onPress: () => {},
  },
  {
    key: 'BAKERY',
    name: 'cupcake',
    type: 'material-community',
    label: 'Bakery',
    onPress: () => {},
  },
  {
    key: 'LATE_NIGHT',
    name: 'owl',
    type: 'material-community',
    label: 'Late Night',
    onPress: () => {},
  },
  {
    key: 'SANDWHICH',
    name: 'food',
    type: 'material-community',
    label: 'Sandwich',
    onPress: () => {},
  },
  {
    key: 'BREWERY',
    name: 'hops',
    type: 'material-community',
    label: 'Brewery',
    onPress: () => {},
  },
  {
    key: 'DOG_FRIENDLY',
    name: 'dog-side',
    type: 'material-community',
    label: 'Dog Friendly',
    onPress: () => {},
  },
  {
    key: 'DELIVERY',
    name: 'truck-fast',
    type: 'material-community',
    label: 'Delivery',
    onPress: () => {},
  },
];
